### ISSUE TITLE
MultiStyles didn't work anymore?

### ISSUE THREAD

**Issue by yokinofile** [nousantx/tenoxui#2]
`MultiStyles` and `MakeStyle` function didn't work anymore? I am using version 0.4.3 which the newest version. I already read the CHANGELOG.md but you are not included the update for the newest version changelog yet maybe?

**Comment by nousantx** [comment]
Oh right. sorry pal, i forgot to include the changelog for the newest version. But, i already include the newest changelog yesterday, maybe you can re-read it again. Also, for `MakeStyle` and `MultiStyles` function, i changed it with new name and use camel case now. Thank you 🙏
