### ISSUE TITLE
Got an error when trying nested in nested style

### ISSUE THREAD

**Issue by yokinox** [nousantx/tenoxui#4]
I want to try nested style using `makeStyles` function but got an error.

file: [tui.js](https://cdn.jsdelivr.net/npm/tenoxui@0.6.0/dist/js/tui.js)

version: [v0.6.0](https://github.com/nousantx/tenoxui/releases/tag/v0.6.0)

code:

```js
makeStyles({
  ".container": {
    "": "p-20px bg-[container-bg] display-flex",
    ".items": {
      "": "fx-200px"
    }
  }
});
```

error: `styles.split is not a function`

**Comment by nousantx** [comment]
Hello friend 👋. Now nested in nested style can be used freely like an object, try this out!!

Solved on v0.6.1
